name: Production
  # 该 JOB 在自建 Runner 中进行运行
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # 该 Job 在自建的 Runner 中执行
    runs-on: self-hosted
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - name: checkout
        uses: actions/checkout@v2
      - name: compose
        run: docker-compose up --build oss -d
      - name: clean images
        run: docker image prune -f
#AW2BO3GH5PMEYI3OISRPOKDEATAVK